- name: "STEP 1 - CONNECT TO OPENSTACK"
  hosts: undercloud
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - DEPLOY TO OPENSTACK"
  hosts: undercloud
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "DEPLOY RESOURCE"
      copy:
        src: stack.sh
        dest: /home/stack/ansible/stack.sh
        mode: '0755'
        follow: yes
- name: "STEP 3 - UPDATE TO OPENSTACK"
  hosts: undercloud
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "RUN SCRIPT"
      shell: /home/stack/ansible/stack.sh
      args:
        chdir: /home/stack/ansible/
      register: result
    - name: "RESULT"
      debug:
        msg: "{{ result.stdout_lines }}"
- name: "STEP 4 - DEPLOY TO ANSIBLE"
  hosts: undercloud
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "FETCH RESOURCE"
      fetch:
        src: /home/stack/ansible/stack.log
        dest: "{{ Project_Path }}"
        flat: yes
      register: result2
    - name: "RESULT"
      debug:
        msg: "{{ result2 }}"
