- name: "STEP 1 - CONNECT TO F5"
  hosts: 10.241.62.104
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"  
- name: "STEP 2 - DEPLOY TO F5"
  hosts: 10.241.62.104
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "DEPLOY RESOURCE"
      copy:
        src: "{{ ANSIBLE_PATH }}/{{ item }}"
        dest: "{{ F5_PATH }}"
        mode: '0755'
        follow: yes
      with_items:
        - stack.log
        - nat.log
        - nat.sh
- name: "STEP 3 - UPDATE TO F5"
  hosts: 10.241.62.104
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "RUN SCRIPT"
      shell: "{{ F5_PATH }}/nat.sh"
      args:
        chdir: "{{ F5_PATH }}"
      register: nat
    - name: "RESULT"
      debug:
        msg: "{{ nat.stdout_lines }}"
        
        
