- name: ANSIBLE RUNNING INFOBLOX
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: INCLUDE VARIABLE BY OTHER YML FILE
      include_vars: INFOBLOX_VAR.yml
    - name: add a comment to an existing A record
      nios_a_record:
        view: "{{ INFOBLOX_SCHOOL_VIEW }}"
        name: "{{ USER_FQDN }}"
        ipv4: "{{ USER_IPV4 }}"
        comment: this is a test comment
        state: present
        provider: "{{nios_provider}}"
        
        
