- name: "STEP 1 - CONNECT TO OPENSTACK"
  hosts: "{{ CONTROLLER0_HOST }}"
  tasks:
    - name: "PING"
      ping:
      register: message
    - name: "RESULT"
      debug:
        msg: "{{ message }}"
- name: "STEP 2 - CREATE OPENSTACK TENANT"
  hosts: "{{ CONTROLLER0_HOST }}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "RUN SCRIPT"
      shell: "{{ OSP_PATH }}/{{ STACK_SCRIPT }}"
      args:
        chdir: "{{ OSP_PATH }}"
      register: result
    - name: "RESULT"
      debug:
        msg: "{{ result.stdout_lines }}"


