#!/bin/bash

TENANT_LOG=$1
PROJECT_VLAN=$2
PROJECT_DESCRIPTION=$3
PROJECT_EXT_SEGMENT_NUM=$4
PROJECT_EXT_IP_24BIT=$5
PROJECT_MANAGE_IP_24BIT=$6

if [ -f ${TENANT_LOG} ]; then
    sudo rm -rf ${TENANT_LOG}
fi

echo "${PROJECT_VLAN}" >> ${TENANT_LOG}
echo "${PROJECT_DESCRIPTION}"  >> ${TENANT_LOG}
echo "${PROJECT_EXT_SEGMENT_NUM}"  >> ${TENANT_LOG}
echo "${PROJECT_EXT_IP_24BIT}"  >> ${TENANT_LOG}
echo "${PROJECT_MANAGE_IP_24BIT}"  >> ${TENANT_LOG}
