- name: Infoblox host search play
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: update an A record name
      nios_a_record:
        name:
          new_name: "test.weses.tyc.edu.tw"
          old_name: "dns.weses.tyc.edu.tw"
        view: ansibleDnsView
        ipv4: 163.30.39.129
        comment: this is a test comment
        state: present
        provider: "{{nios_provider}}"
    - name: remove an A record from the system
      nios_a_record:
        name: "dns.weses.tyc.edu.tw"
        view: ansibleDnsView
        ipv4: 163.30.39.129
        state: absent
        provider: "{{nios_provider}}"
        
