- name: Infoblox host search play
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: Delete a forward DNS zone
      nios_zone:
        name: ansible-test.com
        view: ansibleDnsView
        state: absent
        provider: "{{ nios_provider }}"
