- name: Infoblox host search play
  hosts: localhost
  vars:
    nios_provider:
      host: "{{ INFOBLOX_HOST }}"
      username: "{{ INFOBLOX_USERNAME }}"
      password: "{{ INFOBLOX_PASSWORD }}"
      wapi_version: "{{ WAPI_VERSION }}"
  connection: local
  tasks:
    - name: create host record
      nios_host_record:
        name: star.tyc.edu.tw
        view: ansibleDnsView
        ipv4:
          - address: 10.255.4.10
        state: present
        provider: "{{nios_provider}}"
